// Code generated by assetgen. DO NOT EDIT.

package assets


// Models from models/
const (
	ModelBarrel2 = "barrel2.glb"
	ModelCube = "cube.glb"
	ModelCylinder = "cylinder.glb"
	ModelPlane = "plane.glb"
)

// Shaders from shaders/
const (
	ShaderLightingFS = "lighting.fs"
	ShaderLightingVS = "lighting.vs"
)

