// tools/assetgen/template.go.tmpl
// Code generated by assetgen. DO NOT EDIT.
// Generated at: 2025-11-12T15:16:52+01:00

package assets

// Asset path constants for type-safe asset loading
// Use these constants with the AssetManager to get autocompletion

// Models from models/
const (
	ModelBarrel2  = "barrel2.glb"  // Barrel2
	ModelCube     = "cube.glb"     // Cube
	ModelCylinder = "cylinder.glb" // Cylinder
)

// Shaders from shaders/
// const (
// 	ShaderLighting = "lighting.fs" // Lighting
// 	ShaderLighting = "lighting.vs" // Lighting
// )
