// Code generated by assetgen. DO NOT EDIT.

package assets


// Models from models/
const (
	ModelBarrel2 = "barrel2.glb"
	ModelCube = "cube.glb"
	ModelCylinder = "cylinder.glb"
	ModelPlane = "plane.glb"
	ModelRoom = "room.glb"
)

// Textures from textures/
const (
	TexturePlaceholder = "placeholder.png"
)

// Shaders from shaders/
const (
	ShaderLightingFS = "lighting.fs"
	ShaderLightingVS = "lighting.vs"
	ShaderLightingV2FS = "lighting_v2.fs"
	ShaderLightingV2VS = "lighting_v2.vs"
)

