// Code generated by assetgen. DO NOT EDIT.
// Generated at: 2025-11-13T11:42:02+01:00

package assets


// Models from models/
const (
	ModelBarrel2 = "barrel2.glb"
	ModelCube = "cube.glb"
	ModelCylinder = "cylinder.glb"
)

// Shaders from shaders/
const (
	ShaderLightingFS = "lighting.fs"
	ShaderLightingVS = "lighting.vs"
)

